name: Compilar Trabajo Terminal
on:
  push:
    branches:
      - main

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el repositorio
        uses: actions/checkout@v4
      
      - name: Compilar documento LaTeX
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          args: -pdf -file-line-error -halt-on-error -interaction=nonstopmode

      - name: Renombrar archivo a formato formal
        run: mv main.pdf TT-A214.pdf
          
      - name: Crear enlace permanente para sinodales
        uses: ncipollo/release-action@v1
        with:
          artifacts: "TT-A214.pdf"
          tag: "Borrador-Actual"
          name: "Última versión del Trabajo Terminal"
          body: "Descarga el archivo PDF adjunto para revisar los últimos cambios."
          allowUpdates: true
          replacesArtifacts: true
          token: ${{ secrets.GITHUB_TOKEN }}